apiVersion: rbac.enterprise.mesh.gloo.solo.io/v1
kind: RoleBinding
metadata:
  name: argo-admin-role-binding
  namespace: gloo-mesh
  annotations:
    meta.helm.sh/release-name: gloo-mesh-enterprise
    meta.helm.sh/release-namespace: gloo-mesh
  labels:
    app: gloo-mesh
    app.kubernetes.io/managed-by: Helm
spec:
  roleRef:
    name: admin-role
    namespace: gloo-mesh
  subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: argocd