apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-cert
  namespace: keycloak
spec:
  secretName: keycloak-tls
  commonName: "keycloak.${DOMAIN_NAME}"
  dnsNames:
    - "keycloak.${DOMAIN_NAME}"
  duration: 2160h
  renewBefore: 48h
  issuerRef:
    name: global-letsencrypt-cert-issuer
    kind: ClusterIssuer