apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin-headless
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-headless
  labels:
    app: httpbin-headless
    service: httpbin-headless
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: http
  selector:
    app: httpbin-headless
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-headless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-headless
      version: v1
  template:
    metadata:
      labels:
        app: httpbin-headless
        version: v1
    spec:
      serviceAccountName: httpbin-headless
      containers:
        - name: httpbin-headless
          image: docker.io/kong/httpbin
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              protocol: TCP
              containerPort: 80