apiVersion: v1
kind: ServiceAccount
metadata:
  name: sleep
---
apiVersion: v1
kind: Service
metadata:
  name: sleep
  labels:
    app: sleep
    service: sleep
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: sleep
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: sleep
      containers:
        - name: sleep
          image: curlimages/curl
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "infinity"]
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/sleep/tls
      volumes:
        - name: secret-volume
          secret:
            secretName: sleep-secret
            optional: true
---